import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Navbar from "../../components/Navbar";
import Personnel from "../../components/auth/personnelkey";


export default function Personnelkey() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Personnel Key</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Personnel/>
    </div>
  );
}
